#Generated by Codex (bc I just wanted to do this quickly lol)
#This program feeds the solution steps (PATH_SEQ) into the given netcat server
#and retrieves the flag.

#!/usr/bin/env python3
import socket
import time

HOST = "chall.lac.tf"
PORT = 32223

PATH_SEQ = (
    "sddddswaasdwaaasdssawwdwddsawasassdddwsddwasaaaawwdwdddsawaasassddd"
    "wwdwasssaaawwdwwassdddssddwasaaawwddwdsaaawdsassddwsddwawaawasdddss"
    "awdwaaddwaa"
)

def recv_all(sock, timeout=1.0):
    sock.settimeout(timeout)
    chunks = []
    while True:
        try:
            data = sock.recv(4096)
            if not data:
                break
            chunks.append(data)
        except socket.timeout:
            break
    return b"".join(chunks)

def main():
    payload = (PATH_SEQ + "f\n").encode()

    with socket.create_connection((HOST, PORT), timeout=10) as s:
        # Read banner first
        banner = recv_all(s, timeout=0.5)
        if banner:
            print(banner.decode(errors="replace"), end="")

        # Send input
        s.sendall(payload)

        # Read response (flag)
        time.sleep(0.2)
        resp = recv_all(s, timeout=1.0)
        if resp:
            print(resp.decode(errors="replace"), end="")
        else:
            print("\n(no response after sending input)")

if __name__ == "__main__":
    main()

